#!/usr/bin/sh

build_tool=Ninja

if [ ! -f particule.data ];then
    cd scripts
    python3 binify.py
    cd ..
fi

cmake -B build -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_OPENMP=ON -G $build_tool || exit
cmake --build build || exit

export OMP_NUM_THREADS=$(lscpu -p | egrep -v '^#' | sort -u -t, -k 2,4 | wc -l)
export OMP_PROC_BIND=true
export OMP_PLACES=cores

./build/src/main
